Install: extract rustup and cargo logic into functions

diff --git a/home/dot_config/mh/shared-bin/executable_mh-install b/home/dot_config/mh/shared-bin/executable_mh-install
--- a/home/dot_config/mh/shared-bin/executable_mh-install
+++ b/home/dot_config/mh/shared-bin/executable_mh-install
@@ -7,28 +7,36 @@ function fail {
   exit 1
 }
 
-if ! command -v rustup >/dev/null; then
-    echo "Installing rustup..."
-    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
-    | bash -s -- -y --no-modify-path \
-    || fail "Failed to install rustup"
-fi
+function install_or_update_rustup {
 
-if ! rustup toolchain list | grep nightly >/dev/null; then
-    echo "Adding rust nightly toolchain..."
-    rustup toolchain install nightly \
-    || fail "Failed to install rust nightly toolchain"
-fi
+  if ! command -v rustup >/dev/null; then
+      echo "Installing rustup..."
+      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
+      | bash -s -- -y --no-modify-path \
+      || fail "Failed to install rustup"
+  fi
 
-echo "Updating rustup and Rust toolchains..."
-rustup update || fail "Failed to update rustup"
+  if ! rustup toolchain list | grep nightly >/dev/null; then
+      echo "Adding rust nightly toolchain..."
+      rustup toolchain install nightly \
+      || fail "Failed to install rust nightly toolchain"
+  fi
 
-echo "Installing (or updating) desired cargo binaries..."
-cargo_binaries="${HOME}/.config/mh/desired-state/cargo-binaries"
-[[ -f "$cargo_binaries" ]] || fail "Desired cargo binaries file not found: $cargo_binaries"
+  echo "Updating rustup and Rust toolchains..."
+  rustup update || fail "Failed to update rustup"
+}
 
-for binary in $(sed -e 's@#.*@@g' < "$cargo_binaries" | xargs); do
-  echo "Installing (or updating) cargo binary: $binary"
-  cargo install "$binary" \
-  || fail "Failed to install or update cargo binary: $binary"
-done
+function install_or_update_cargo {
+  echo "Installing (or updating) desired cargo binaries..."
+  cargo_binaries="${HOME}/.config/mh/desired-state/cargo-binaries"
+  [[ -f "$cargo_binaries" ]] || fail "Desired cargo binaries file not found: $cargo_binaries"
+
+  for binary in $(sed -e 's@#.*@@g' < "$cargo_binaries" | xargs); do
+    echo "Installing (or updating) cargo binary: $binary"
+    cargo install "$binary" \
+    || fail "Failed to install or update cargo binary: $binary"
+  done
+}
+
+install_or_update_rustup
+install_or_update_cargo
