Install: install (or update) desired cargo binaries

diff --git a/home/dot_config/mh/shared-bin/executable_mh-install b/home/dot_config/mh/shared-bin/executable_mh-install
--- a/home/dot_config/mh/shared-bin/executable_mh-install
+++ b/home/dot_config/mh/shared-bin/executable_mh-install
@@ -22,3 +22,10 @@ fi
 
 echo "Updating rustup and Rust toolchains..."
 rustup update || fail "Failed to update rustup"
+
+echo "Installing (or updating) desired cargo binaries..."
+desired_cargo_binaries=$(cat ~/.config/mh/desired-state/cargo-binaries)
+for binary in "${desired_cargo_binaries[@]}"; do
+  cargo install "$binary" \
+  || fail "Failed to install or update cargo binary: $binary"
+done
