Install: fail-fast for each step

diff --git a/home/dot_config/mh/shared-bin/executable_mh-install b/home/dot_config/mh/shared-bin/executable_mh-install
--- a/home/dot_config/mh/shared-bin/executable_mh-install
+++ b/home/dot_config/mh/shared-bin/executable_mh-install
@@ -2,19 +2,26 @@
 
 # Installs core software, taking into account desired state
 
+function fail() {
+  echo "$1" >&2
+  exit 1
+}
+
 if ! command -v rustup >/dev/null
 then
     echo "Installing rustup..."
     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
-    | bash -s -- -y --no-modify-path
+    | bash -s -- -y --no-modify-path \
+    || fail "Failed to install rustup"
 fi
 
 if ! rustup toolchain list | grep nightly >/dev/null
 then
     echo "Adding rust nightly toolchain..."
-    rustup toolchain install nightly
+    rustup toolchain install nightly \
+    || fail "Failed to install rust nightly toolchain"
 fi
 
 # Update Rust toolchains and rustup
 echo "Updating rustup..."
-rustup update
+rustup update || fail "Failed to update rustup"
