MAYBE? bu_ok in git workflow? better would be to sep into 'bu' target
bu ok tag in workflow

diff --git a/home/dot_config/mh/shared-bin/executable_mh-git-workflow-rebase-dotfiles b/home/dot_config/mh/shared-bin/executable_mh-git-workflow-rebase-dotfiles
--- a/home/dot_config/mh/shared-bin/executable_mh-git-workflow-rebase-dotfiles
+++ b/home/dot_config/mh/shared-bin/executable_mh-git-workflow-rebase-dotfiles
@@ -61,6 +61,12 @@ function update_base_tag_for_branch_or_fail {
   fi
 }
 
+function bu_ok_tag {
+  git rev-parse --quiet --verify ok >/dev/null || fail "Tag 'ok' not found"
+  git branch -f bu-ok ok || fail "Failed to set bu-ok branch to ok tag"
+  git push -f -u origin bu-ok || fail "Failed to push bu-ok branch"
+}
+
 function main {
   assert_git_repo
   git remote get-url origin | grep 'mbhutton/dotfiles' >/dev/null \
@@ -75,6 +81,8 @@ function main {
   assert_a_is_ancestor_of_b origin/main main
   assert_a_is_ancestor_of_b main ok
   assert_a_is_ancestor_of_b ok dev
+
+  bu_ok_tag
 
   if ! is_a_ancestor_of_b _dev4off off; then
     if is_a_ancestor_of_b dev off; then
