Silently continue when trying to load prezto files if prezto not yet installed

diff --git a/home/dot_config/zsh/dot_zshenv b/home/dot_config/zsh/dot_zshenv
--- a/home/dot_config/zsh/dot_zshenv
+++ b/home/dot_config/zsh/dot_zshenv
@@ -27,7 +27,8 @@ function source_prezto_runcoms {
     return 1
   fi
   if [[ ! -d "${ZDOTDIR}/.zprezto" ]]; then
-    echo "Prezto directory not found at ${ZDOTDIR}/.zprezto"
+    echo "Prezto directory not found at ${ZDOTDIR}/.zprezto, so not sourcing $1" >&2
+    return 0
   fi
 
   local filename
